# =============================================================================
# Cert-Manager Namespace
# Automated TLS certificate management with Let's Encrypt
# =============================================================================

---
apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager
    labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/component: certificate-management
        app.kubernetes.io/managed-by: k3s-vps
        # PSA: baseline for cert-manager
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
