# =============================================================================
# Infrastructure Namespaces
# Base namespaces for shared infrastructure services
# =============================================================================

---
apiVersion: v1
kind: Namespace
metadata:
    name: storage
    labels:
        app.kubernetes.io/name: storage
        app.kubernetes.io/component: infrastructure
        app.kubernetes.io/managed-by: k3s-vps
        # PSA: privileged for storage services (PostgreSQL needs specific caps)
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted

---
apiVersion: v1
kind: Namespace
metadata:
    name: security
    labels:
        app.kubernetes.io/name: security
        app.kubernetes.io/component: infrastructure
        app.kubernetes.io/managed-by: k3s-vps
        # PSA: baseline for Keycloak (may need some caps)
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted

---
apiVersion: v1
kind: Namespace
metadata:
    name: monitoring
    labels:
        app.kubernetes.io/name: monitoring
        app.kubernetes.io/component: infrastructure
        app.kubernetes.io/managed-by: k3s-vps
        # PSA: baseline for monitoring (node-exporter needs hostNetwork/hostPID)
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: baseline
        pod-security.kubernetes.io/warn: baseline
